= ScreamAPI

_Legit DLC Unlocker for Epic Online Services_

== ✨ Features

* 🔓 Legit DLC Unlocking
* 🛅 Entitlements emulation
* ⌚ Playtime blocking
* 2️⃣ Installation methods:
** 🪝 Hook mode
** 🔀 Proxy mode

== 🔗 Links

:forum-topic: https://cs.rin.ru/forum/viewtopic.php?p=2161197#p2161197[ScreamAPI forum topic]

* 📥 https://github.com/acidicoala/ScreamAPI/releases/latest[Download the latest release]
* 💬 {forum-topic}
* 🗂️ https://scream-db.web.app[DLC Database]

== 📖 Introduction

=== What is ScreamAPI?

ScreamAPI is a DLC unlocker for the games that are legitimately owned in your Epic Games account.
It attempts to fool games that use Epic Online Services Software Development Kit (EOSSDK) into thinking that you own the desired DLCs.
However, ScreamAPI does not modify the rest of the EOSSDK, hence features like multiplayer, achievements, etc. remain fully functional.

.Which games are supported?
[%collapsible]
====
Only games that use Epic Online Services Software Development Kit (EOS SDK) for the DLC ownership verification are supported.
So if a game's installation directory does not contain any _EOSSDK-WinXX-Shipping.dll_ files, then it's definitely not supported.
Even if the game uses EOS SDK DLL, it's not guaranteed to be supported because each game might implement its own additional verification checks.
Therefore, you have to first research the game's topic, to see if it supports unlocking.

Additionally, there are several points to bear in mind when it comes to ScreamAPI and Epic Games Store:

* ScreamAPI most definitely will not work with games that use 3rd party DRM, such as games from Ubisoft, Rockstar, etc.
Furthermore, ScreamAPI is also unlikely to unlock anything in Free-To-Play games since they typically store all player data on the corresponding game server and hence all the checks are server-side.
* ScreamAPI will not work with games that employ additional ownership protection or if the game is using alternative DLC verification mechanism (like Borderlands 3).
However, it can unlock DLCs in Denuvo-protected games if there are no other integrity checks (like Death Stranding)
* ScreamAPI is unlikely to work with games that use an anti-cheat, since they typically detect any DLL/EXE that has been tampered with.
Sometimes it is possible to disable an anti-cheat, but that typically entails the loss of online capabilities.
Search in the respective game topic for more information about how to disable anti-cheat.
* Some games include the DLC files in their base game, regardless of whether you own the DLC or not (like World War Z).
This is the ideal scenario for ScreamAPI.
However, some games download additional files only after a user has bought the corresponding DLC (like Civilization VI).
In this case, not only you will need to install ScreamAPI, but you also have to get the additional DLC files elsewhere and put them into the game folder.
* Some games don't use any DRM at all, in which case ScreamAPI is useless.
All you need to do is to get the DLC files elsewhere and put them into the game folder.
====

== 🛠 Installation Instructions

WARNING: Please proceed with installation at your own risk.
Usage of this unlocker entails breaking one or more terms of service, which might result in a permanent loss of your account.

ScreamAPI is loaded into a game process, which limits it to that particular game only.
ScreamAPI supports 2 installation modes: hook mode and proxy mode.

|===
|Mode |Advantages |Disadvantages

|🪝 Hook mode
|Persists after game updates; Can be loaded by other injectors.
|Might need an additional DLL (Koaloader)

|🔀 Proxy mode
|Guaranteed to load
|Might need reinstallation if Steam updates affected DLL files

|===

Try installing the unlocker in hook mode first.
If it doesn't work, try installing it in proxy mode.

:koaloader: https://github.com/acidicoala/Koaloader[Koaloader]
:screamapi_release: https://github.com/acidicoala/ScreamAPI/releases/latest[ScreamAPI Releases]

=== 🪝 Hook mode

. Download the latest ScreamAPI release zip from {screamapi_release}.
. From ScreamAPI archive unpack `ScreamAPI32.dll` / `ScreamAPI64.dll`, depending on the game bitness
. Rename the unpacked DLL to `version.dll`.
. Place `version.dll` next to the game's `.exe` file.

=== 🪝 Hook mode (Alternative installation)

:special_k: https://www.special-k.info[Special K]
:custom_plugin: https://wiki.special-k.info/en/SpecialK/Tools#custom-plugin[custom plugin]

If a game doesn't load `version.dll`, you can use one of the {koaloader} DLLs that the game does in fact load.
For example, assuming that the game loads `winmm.dll`:

. Download the latest Koaloader release zip from https://github.com/acidicoala/Koaloader/releases/latest[Koaloader Releases].
. From Koaloader archive unpack `winmm.dll` from `winmm-32` or `winmm-64`, depending on the game bitness, and place it next to the game exe file.
. Download the latest ScreamAPI release zip from {screamapi_release}.
. From ScreamAPI archive unpack `ScreamAPI32.dll` / `ScreamAPI64.dll`, depending on the game bitness.
. Place the unpacked DLL next to the game's `exe` file.

[[special_k_note]]
IMPORTANT: There are games which have extra protections that break hook mode.
In such cases, it might be worth trying {special_k}, which can inject ScreamAPI as a {custom_plugin}.

==== 🔀 Proxy mode

. Find `steam_api.dll` / `steam_api64.dll` file in game directory, and rename it to `steam_api_o.dll` / `steam_api64_o.dll`.
. Download the latest ScreamAPI release zip from  {screamapi_release}.
. From ScreamAPI archive unpack `ScreamAPI32.dll` / `ScreamAPI64.dll`, depending on the game bitness.
. Rename the unpacked DLL to `steam_api.dll` / `steam_api64.dll` and place it next to the `steam_api_o.dll` / `steam_api64_o.dll` file.

NOTE: There are games which have extra protections that break proxy mode.
In such cases, see the note on <<special_k_note, Hook mode with Special K>>

'''

IMPORTANT: When a game opens a web page on Epic Games website, which asks your permission to share your profile info with the game, you need to accept that for the DLC unlocking to work properly.
Many games simply don't start DLC ownership checks until they have received this permission.

If the unlocker is not working as expected, then please fully read the https://gist.github.com/acidicoala/2c131cb90e251f97c0c1dbeaf2c174dc[Generic Unlocker Installation Instructions] before seeking support in the {forum-topic}.

== ⚙ Configuration
:fn-dlc-id: footnote:fn-app-id[DLC IDs can be obtained from https://scream-db.web.app.]

ScreamAPI does not require any manual configuration.
By default, it uses the most reasonable options and tries to unlock all DLCs that it can.
However, there might be circumstances in which you need more custom-tailored behaviour, such as disabling certain DLCs, or selectively enabling just a few of them.
In this case you can use a configuration file link:res/ScreamAPI.config.json[ScreamAPI.config.json] that you can find here in this repository or in the release zip.
To use it, simply place it next to the ScreamAPI DLL.
It will be read upon each launch of a game.
In the absence of the config file, default values specified below will be used.
The configuration file is expected to conform to the Json standard.

:bool-values: pass:q[`true` or `false`]
:default-string-value: pass:q[`""` (Empty string)]
:default-object-value: pass:q[`{}` (Empty object)]
:id-values: 32-character hex string
:dlc-status-values: pass:q[`"unlocked"` or `"locked"` or `"original"`]

|===
|Option |Description| Type |Default |Valid values

|`logging`
|Enables logging to `ScreamAPI.log.log` file.
|Boolean
|`false`
|{bool-values}

|`log_eos`
|Enables or disables interception of EOS SDK logs. Required `logging` to be enabled.
|Boolean
|`false`
|{bool-values}

|`block_metrics`
|Blocks reporting of analytics and usage metrics by the game to Epic Online Services. Metrics sent by EOS SDK itself remain unaffected.
|Boolean
|`false`
|{bool-values}

|`namespace_id`
|Namespace ID of the game that is used when fetching entitlements. Normally ScreamAPI will automatically get this during EOS SDK initialization. However, in case of late injection, where ScreamAPI is injected after EOS SDK is initialized, this option can be used to provide the game's namespace ID. .
|String
|{default-string-value}
|Namespace ID of any game can be found on https://scream-db.web.app[ScreamDB].

|`default_dlc_status`
|Specifies default DLC status
|String
|`"unlocked"`
|{dlc-status-values}

|`override_dlc_status`
|Overrides the status of individual DLCs
|Object
|{default-object-value}
|An object with `"key": "value"` pairs, where key is DLC ID{fn-dlc-id} ({id-values}) and value is DLC status ({dlc-status-values}).

|`extra_graphql_endpoints`
|When a game requests all available entitlements ScreamAPI has to make a request to a valid Epic Games GraphQL endpoint to fetch this information. This means that when Epic Games changes their endpoints, ScreamAPI loses ability to automatically fetch entitlements. This where this option becomes useful, allowing users to specify latest GraphQL endpoint (or several).
|Array
|`[]` (Empty array)
|An array of valid GraphQL endpoints (`["https://..."]`)

|`extra_entitlements`
|Additional entitlements that ScreamAPI will inject when a game requests all entitlements owned by the player. There is usually no need to manually entitlement IDs because ScreamAPI will automatically fetch them from Epic Games Store servers. However, if the servers are not accessible then this option becomes useful.
|Object
|{default-object-value}
|An object with `"key": "value"` pairs, where key is DLC ID{fn-dlc-id} ({id-values}) and value is DLC title. Title is used only for logging, hence it can be left empty (i.e. `""`).
|===

.Advanced options
[%collapsible]
====

NOTE: These options do not affect the unlocker, and should be left unmodified.
They serve as utilities for text or GUI editors.

|===
|Option |Description| Type |Default |Valid values

|`$schema`
|URL of a JSON Schema that corresponds to this config.
|String
|https://raw.githubusercontent.com/acidicoala/ScreamAPI/refs/tags/v3.1.0/res/ScreamAPI.schema.json[ScreamAPI.schema.json]
|URL to a valid ScreamAPI config JSON schema

|`$version`
|Reserved for use by tools like GUI config editors.
|Integer
|`3`
|Integer numbers from 1 and beyond
|===

====

Below you can find an example config where nearly each option has been customized

.Complete example
[%collapsible]
====
[source,json]
----
{
  "$schema": "https://raw.githubusercontent.com/acidicoala/ScreamAPI/refs/tags/v3.1.0/res/ScreamAPI.schema.json",
  "$version": 3,
  "logging": true,
  "log_eos": true,
  "block_metrics": true,
  "namespace_id": "catnip",
  "default_dlc_status": "unlocked",
  "override_dlc_status": {
    "12f2fca1c9304897b581254a0913ac51": "original",
    "6a3c06879500496b853726573b896dff": "unlocked",
    "3a6a3f9b351b4b599808df3267669b83": "locked"
  },
  "extra_graphql_endpoints": [
    "https://launcher.store.epicgames.com/graphql",
    "https://graphql.unrealengine.com/ue/graphql"
  ],
  "extra_entitlements": {
    "fa7463c069a74d07aadf315df9b4e28b": "Big Top Breakout",
    "89867f8b0e79421698e4705a72a48b49": "Dungeons and Duct Tape"
  }
}
----
====

== Extra info

=== When does ScreamAPI handle entitlement requests?

When a game requests a list of entitlements that user owns, it may specify an optional list of entitlement IDs.
The EOS SDK is supposed to respond only with entitlements that match these IDs.
Hence, ScreamAPI can use this information to generate a response which contains all entitlements specified by the game.
However, if a game does not provide a list of entitlement IDs then ScreamAPI has to resort to making a request to Epic Games Store servers to retrieve all offered DLCs, whose IDs will be used to generate a response.

== 🏗️ Building from source

Refer to https://github.com/acidicoala/SmokeAPI#%EF%B8%8F-building-from-source[SmokeAPI Readme] for instructions, as they are the equivalent.

== 📚 Open-Source libraries

This project makes use of the open source projects specified in the https://github.com/acidicoala/KoalaBox#-open-source-libraries[KoalaBox Readme].

== 📄 License

This software is licensed under the https://unlicense.org/[Unlicense], terms of which are available in link:UNLICENSE.txt[UNLICENSE.txt]
