name: Continuous Integration
on: push

jobs:
  build-and-release:
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@3008dcf70ad9e18ecb19ddac9df783928f3f7b53
    permissions:
      contents: write
    with:
      modules: >-
        ["ScreamAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        extra/README.txt
        res/ScreamAPI.json
