name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@b28cf2aed819a183298c832d4e4cc6d298bbf55c
    permissions:
      contents: write
    with:
      arch: '[ 32, 64 ]'
      config: Release
      modules: '[ "ScreamAPI" ]'
      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        res/ScreamAPI.config.json
        res/README.txt
