name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@fe45f9c61c6ff227b79c72624d8ab4cb8dc5a403
    permissions:
      contents: write
    with:
      modules: >-
        ["ScreamAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        extra/README.txt

      config: Debug
