name: Continuous Integration
on: push

jobs:
  build-and-release:
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@9d5f4fb5617cfa090e49ab6dd0b20951f0bcb1b5
    permissions:
      contents: write
    with:
      modules: >-
        ["ScreamAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        extra/README.txt
        res/ScreamAPI.json
