name: Continuous Integration
on: push

jobs:
  build-and-release:
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@242e86f7e40189f5526710fc32ef4de95d8e0ea8
    permissions:
      contents: write
    with:
      modules: >-
        ["ScreamAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        extra/README.txt
        res/ScreamAPI.json
