name: Continuous Integration
on: push

jobs:
  build-and-release:
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@3e25f0fe17e4ae2e8ee9f44a5ef31781a10a556a
    permissions:
      contents: write
    with:
      modules: >-
        ["ScreamAPI"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        extra/README.txt
        res/ScreamAPI.json
